### ISSUE TITLE
Add `zerocopy::byteorder::NE` typealias for `zerocopy::byteorder::NativeEndian`

### ISSUE THREAD

**Issue by daprilik** [google/zerocopy#100]
Title says it all.

`U32<NativeEndian>` is a real mouthful, and working around it by including `type NE = NativeEndian;` in each file it gets used in would be really unfortunate...

If I had to guess, the reason this doesn't exist yet was because it might lead to confusion with `NetworkEndian`? That's just a guess of course, but in case that's right: I don't think it's too confusing, given that the Rust standard library already has the convention of implementing methods in triples of `be`/`le`/`ne` (e.g: `uXX::{to,from}_{be,le,ne}_bytes()`)

**Comment by joshlf** [comment]
The existing aliases are actually just included wholesale from the `byteorder` crate, which only provides `BE` and `LE` aliases. I'm working on a feature to make this nicer to work with, but in the meantime, what I've done in codebases that use zerocopy is, at the crate root:

```
type U32 = zerocopy::U32<NativeEndian>;
```

And then, in file that make use of that type, just do `use crate::U32`.

**Comment by daprilik** [comment]
Cool, that works too, thanks!

**Comment by joshlf** [comment]
np!
