### ISSUE TITLE
Fix cfgs in rustdoc

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#1055]
`FromZeros::new_vec_zeroed` has the wrong `cfg` rendered on docs.rs:

<img width="1002" alt="image" src="https://github.com/google/zerocopy/assets/1046063/617b679e-1584-4e84-8345-49f9abeaa1d4">

We emit the wrong `doc_cfg` attribute:

https://github.com/google/zerocopy/blob/2bec60bc93683dcbe8da6a7417b6326783e7a61b/src/lib.rs#L1943-L1946

We should fix this and also figure out whether there are other incorrect `doc_cfg` items to fix while we're here.

## Mentoring instructions

Find and fix any instance of `doc_cfg` that doesn't match the corresponding `cfg` attribute.

**Comment by whee** [comment]
FWIW, I looked at the state of `doc_cfg` items in `main` at 5b99dc3ed47737fa6189c965874c79c52a59e27e and did not see any mismatches anywhere.

The item mentioned here was fixed in e56a42b87e4b4550c81741534634558ba6c2adf4.

**Comment by joshlf** [comment]
Huh, seems you're right. Cool.
