### ISSUE TITLE
Fix breakage stemming from Syn MSRV bump

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#1085]
Starting with #1081, our nightly toolchain roller began to fail. The cause was syn increasing its MSRV to 1.60 from 1.56. Our MSRV remains at 1.56, so CI builds on that toolchain began to fail to resolve a suitable version of syn.

The timeline of events on syn's side is a little confusing:
1. March 21: [Raise required compiler to rust 1.60 ](https://github.com/dtolnay/syn/commit/0b2b498fa5d48c4ae78c9dbe6f73423c209d87c8)
2. March 23: [Release 2.0.54](https://github.com/dtolnay/syn/commit/a5d02b1afe7641dfaadd660be32bb9822b74f47b)
3. March 23: [Restore compatibility with rustc 1.56 through 1.59
](https://github.com/dtolnay/syn/commit/6e8a372d605af4af48d4b3dcf2f41792777f2b67)
4. March 23: [Release 2.0.55](https://github.com/dtolnay/syn/commit/d4c4811bd58fd22b4cc68988166aee2132ffb3be)
5. March 29: [chore: bump msrv to 1.60](https://github.com/dtolnay/syn/commit/4913ab2fe69d03a0a1821dc6c40fe6fabfc44d8f) in https://github.com/dtolnay/syn/pull/1608
6. March 29: [Release 2.0.56](https://github.com/dtolnay/syn/commit/3c07b7847b730380c16bcef5213a8c685a379a40)

Not yet sure how we should proceed with this. A few possibilities that spring to mind:
- We build in CI with `-Z minimal-versions`
- We downgrade to syn 1.x (MSRV is 1.31)
- We vendor (or reimplement) the parts of syn relevant to zerocopy-derive
- We delete our MSRV policy on zerocopy-derive; we cannot guarantee an MSRV for that crate, since it has dependencies with different MSRV policies. 
- Ask syn to adopt a more conservative MSRV policy.

**Comment by weihanglo** [comment]
Could also consider committing a MSRV compatible `Cargo.lock`, so it becomes a source of true of what is buildable. And Optionally have a non-blocking "latest version" job for verification purpose.

See also [Verifying rust-version](https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-rust-version) and [Verifying Latest Dependencies](https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-latest-dependencies) for some CI pracitices.

**Comment by joshlf** [comment]
I've put up a PR to temporarily pin syn to a known-good version so that we can unblock CI: https://github.com/google/zerocopy/pull/1089. That's obviously not a complete fix, so I've filed https://github.com/google/zerocopy/issues/1088 and blocked releasing 0.8 (https://github.com/google/zerocopy/issues/671) on it.

**Comment by joshlf** [comment]
Update: [this is now affecting 0.7](https://github.com/google/zerocopy/actions/runs/9648363429/job/26609597418) after syn 2.0.68 bumped its MSRV from 1.60 (which is zerocopy 0.7's MSRV) to 1.61.
