### ISSUE TITLE
Unconditionally implement `FromBytes for MaybeUninit<T>`?

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#117]
`MaybeUninit` has no bit validity requirements. Thus, technically, `MaybeUninit<T>` satisfies the requirements for `FromBytes` even if `T` doesn't. Should we implement `FromBytes` for `MaybeUninit<T>`? Even if it's sound, it might still be a big footgun. Will need to think this one through...

**Comment by reynoldsbd** [comment]
Had the same thought while perusing your docs!

An interesting use case would be `LayoutVerified<B, MaybeUninit<T>>`, which could be used to allocate a new `T` backed by storage from a plain `&mut [u8]`. However, without a usable implementation of `AsBytes`, it would not be possible to call `MaybeUninit::write()` (which requires `&mut self`)
