### ISSUE TITLE
Debug GitHub Actions issue

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#1276]
I've been working on #1275, and haven't been able to get the added script in `actions/zerocopy_toolchain_version/action.yml` to produce output usable by `workflows/ci.yml`. In particular, `${{ steps.toolchain.outputs.toolchain }}` always interpolates to an empty string.

I'd love it if someone with more GitHub Actions experience could take a look and see if they can figure out what's going wrong!

**Comment by sl4m** [comment]
It looks like adding the following [here](https://github.com/google/zerocopy/blob/f9f2cf59775337ef3eda51d33ebe956aa48d6136/.github/actions/zerocopy_toolchain_version/action.yml#L14) seems to do the trick:

```
outputs:
  toolchain:
    description: 'Resolved toolchain version'
    value: ${{ steps.resolve.outputs.toolchain }}
```

I followed the example from the [doc](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file).

[Test run](https://github.com/sl4m/zerocopy/actions/runs/9355599625) on my fork.

Note: I didn't see this as a GitHub issue, so wanted to flag the `target` clean up errors in this test run.

<img width="909" alt="Target clean up errors" src="https://github.com/google/zerocopy/assets/47347/a223f997-d1d2-4df2-b2c7-2dc7e1288d3a">

Originally, I thought I introduced these with the code change, but the errors appear in the official test runs as well. [Example](https://github.com/google/zerocopy/actions/runs/9351378233). It appears to be an issue with the action `Swatinem/rust-cache`, but haven't look into it further.

**Comment by joshlf** [comment]
Amazing, thank you! I've also opened #1389 based on your observation about the `target` dir errors.
