### ISSUE TITLE
Add positive and negative trait impl tests for SIMD types

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#130]
We have tests to ensure that our implementations of `FromBytes`, `AsBytes`, and `Unaligned` for various primitive does not regress:
https://github.com/google/zerocopy/blob/3bb9a54ff458e104f7eb24beda7f8fb09794e1a5/src/lib.rs#L4512-L4517

**We should have similar tests for our implementations (or lack thereof) for SIMD types.**  

## Mentorship Instructions
To do this, we will be adding tests at the end of `test_impls`: https://github.com/google/zerocopy/blob/b083f1f12839b91a54460ab5d2518105f3fc5355/src/lib.rs#L4488-L4584

At the bottom of that test function, create a new block annotated with `#[cfg(simd)]`; e.g.:
```rust
#[cfg(feature = "simd")]
{
    /* everything else will go in this block */
}
```
Then, add a macro definition like this:
```rust
/// Tests that the given SIMD types (belonging to some given architecture)
/// implement exactly the expected set of traits.
macro_rules! test_simd_arch_mod {
    ($arch:ident, $($typ:ident),*) => {
        {
            use core::arch::$arch::{$($typ),*};
            use crate::*;
            $( assert_impls!($ty: KnownLayout, FromZeroes, FromBytes, AsBytes, !Unaligned); )*
        }
    };
}
```
Finally, invoke the macro for each of the SIMD-supporting architectures (see [here](https://github.com/google/zerocopy/blob/b083f1f12839b91a54460ab5d2518105f3fc5355/src/lib.rs#L1587-L1622)); e.g.:
```rust
#[cfg(target_arch = "x86")]
test_simd_arch_mod!(x86, __m128, __m128d, __m128i, __m256, __m256d, __m256i);
#[cfg(target_arch = "x86_64")]
test_simd_arch_mod!(x86_64, __m128, __m128d, __m128i, __m256, __m256d, __m256i);

/* and so on */
```

**Comment by friendlymatthew** [comment]
Hi @joshlf has this gone stale?

**Comment by Sh0g0-1758** [comment]
Hey, can I work on this issue?

**Comment by shyamjayakannan** [comment]
Hi, are you looking for a test similar to the one for primitives, to be written within the simd module following all the impls?

**Comment by jswrenn** [comment]
Apologies, everyone — we'd like to take a slightly different approach. I've updated the issue accordingly.

**Comment by jswrenn** [comment]
@shyamjayakannan: I'll assign this to @Sh0g0-1758 since they commented first, but you're welcome to take it if they don't end up working on it.

**Comment by Sh0g0-1758** [comment]
thanks, @jswrenn, I will make sure to complete it.

**Comment by shyamjayakannan** [comment]
@Sh0g0-1758, I have been working on this issue and am nearing completion. Could you allow me to contribute to this issue?

**Comment by Sh0g0-1758** [comment]
@jswrenn , I have made a PR. Kindly review it and suggest changes.

**Comment by joshlf** [comment]
Closed by https://github.com/google/zerocopy/pull/487.
