### ISSUE TITLE
CI cache not including installed Cargo tools?

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#1312]
Our `generate_cache` CI job, which is a dependency of the main `build_test` job, runs [`cargo install cargo-nextest`](https://github.com/google/zerocopy/blob/889ac1bc2f38b1ccf338a1bf12f222102b338bc0/.github/workflows/ci.yml#L476). However, in [this run](https://github.com/google/zerocopy/actions/runs/9149280094/job/25152797173?pr=1311), we can see that it's getting re-installed in `build_test`. This likely means that binaries installed via `cargo install` are not getting cached.

**Comment by sl4m** [comment]
Is it possible it's due to the `cargo clean` call? I see the job you linked matches the target specified here: https://github.com/google/zerocopy/blob/889ac1bc2f38b1ccf338a1bf12f222102b338bc0/.github/workflows/ci.yml#L249C23-L256.

Note: Saw this issue from _This Week in Rust_

**Comment by joshlf** [comment]
Credit to @sl4m for figuring out that this was actually a red herring (https://github.com/google/zerocopy/pull/1375#issuecomment-2143174514):

> > Amazing, thank you for fixing this! I'm not sure I understand why this fix works, though?
> 
> Ok, I think I know what's really going on. My change worked in my fork because I did not have existing caches.
> 
> I believe `cargo-nextest` was recently introduced in #1307? If so, it may be a result of an old cache. A new cache is created only if `Cargo.toml` changes (see [here](https://github.com/google/zerocopy/blob/4b18d5b490b159abb72ded9fc334ea1a3025eae2/.github/actions/cache/action.yml#L18)) and since GitHub Actions cache are [immutable](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache), it did not preserve the `cargo-nextest` installation.
> 
> `Cargo.toml` has since been updated via google-pr-creation bot, so the caches should now have `cargo-nextest`.
> 
> I checked a [recent build](https://github.com/google/zerocopy/actions/runs/9323668480/job/25667424858) and it looks like it's ignoring the `cargo-nextest` installation as expected:
> 
> ```
> Running Miri tests with 8 threads
>     Updating crates.io index
>      Ignored package `cargo-nextest v0.9.72` is already installed, use --force to override
> Preparing a sysroot for Miri (target: aarch64-unknown-linux-gnu)... done
> ```
> 
> I think I will close this PR if you agree and you can probably close #1312.
