### ISSUE TITLE
Are we accidentally publishing our `Cargo.lock` files?

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#135]
When we published 0.7.0-alpha.2, [this Cargo.lock file](https://docs.rs/crate/zerocopy/0.7.0-alpha.2/source/Cargo.lock) got included. Is this problematic? Should we avoid it?

**Comment by AntoniosBarotsis** [comment]
I don't think it matters *too* much but the [official docs](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) mention how libraries should **not** include lockfiles.

**Comment by joshlf** [comment]
It looks like that's about version control, not publishing on crates.io. We don't check in `Cargo.lock` to this git repo. My guess is that `cargo publish` scooped it up automatically, although I'm surprised that Cargo isn't configured to automatically ignore `Cargo.lock` files (like it already does for the `target` directory). We may need to add it to our `exclude` line. Then again, it may have no effect at all (in other words, Cargo may ignore `Cargo.lock` files in dependent crates), so maybe we don't need to do anything.

More broadly, it might be worth having a more principled approach to what to include/exclude, and perhaps test that the right things are included/excluded in CI. Not sure how to do that and whether it'd be worth the complexity, whether we could prevent it from becoming stale, etc. I'm worried about including the wrong things (like `Cargo.lock`) but I'm _more_ worried about excluding or failing to include the wrong things (like a source file).

**Comment by joshlf** [comment]
I just ran `cargo package` locally and confirmed that `Cargo.lock` isn't getting included. This must be automatically generated by crates.io or during `cargo publish` or something. Doesn't seem like it's causing anyone problems, so I'm gonna close this for now.
