### ISSUE TITLE
`DerefMut` is not implemented for `Ref<B, T>` if `T` is a DST

### ISSUE THREAD

**Issue by CJKay** [google/zerocopy#1445]
I'm experimenting with zerocopy 0.8.0-alpha.14 as the format I need to deserialize has a dynamically-sized header. Everything works great for immutable access, but mutability appears to be a problem for DSTs even where I'm quite sure it is sound.

The problem is that [`Ref<B, T>` only implements `DerefMut` where `T` implements `IntoBytes`](https://google.github.io/zerocopy/src/zerocopy/ref.rs.html#896-922). DSTs cannot implement `IntoBytes` because their size is obviously not statically known. Therefore any `Ref<B, T>` where `T` is dynamically-sized cannot implement `DerefMut`.

Is this an intended limitation?

**Comment by jswrenn** [comment]
DSTs are challenging because not only do they have dynamic size, but also dynamic padding. Consider a type like this:
```rust
#[repr(C)]
struct Foo {
    header: u8,
    slice: [u8]
}
```
...which will only be free of padding bytes for odd sizes of `slice`.

The good news is that our analysis handles such types, so long as they're `packed`:
```rust
#[derive(KnownLayout, IntoBytes)]
#[repr(C, packed)]
struct Foo {
    header: u8,
    slice: [u8]
}
```

**Comment by CJKay** [comment]
Ah, I wasn't aware slices were dynamically-padded. This works, thanks!
