### ISSUE TITLE
Ord instances for integer wrappers e.g. U64

### ISSUE THREAD

**Issue by jjl** [google/zerocopy#148]
It would be nice if they could be compared directly rather than having to `.get()` them before comparison. That would allow deriving Ord over structs using them that are in disk format.

**Comment by joshlf** [comment]
If memory serves, I tried this when I initially introduced those wrappers, and it caused a lot of type inference issues. I'll take a stab at it again when I get a chance to confirm that that was the reason.

**Comment by joshlf** [comment]
Closed in https://github.com/google/zerocopy/issues/1120.
