### ISSUE TITLE
`where_clauses_object_safety` future compatibility lint warning

### ISSUE THREAD

**Issue by andrewpollack** [google/zerocopy#150]
Using the latest `zerocopy-0.7.0-alpha.2` release on rustc ToT  ([83a28ef095ba4179a63196f16eadd97f110d6cb3](https://github.com/rust-lang/rust/commit/83a28ef095ba4179a63196f16eadd97f110d6cb3)) is leading to the following warning around future compatibility:

```
error: the trait `AsBytes` cannot be made into an object
 --> zerocopy-0.7.0-alpha.2/src/lib.rs:608:8
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #51443 <https://github.com/rust-lang/rust/issues/51443>
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
 --> zerocopy-0.7.0-alpha.2/src/lib.rs:608:8
  |
  = note: the trait cannot be made into an object because method `as_bytes_mut` references the `Self` type in its `where` clause
```

See https://github.com/rust-lang/rust/issues/51443 for more context on this future compatibility lint.

**Comment by andrewpollack** [comment]
Also, see https://github.com/rust-lang/rust/issues/102546 for issues on `where_clauses_object_safety ` lint diagnostics

**Comment by joshlf** [comment]
https://github.com/rust-lang/rust/issues/51443#issue-330805907 says:

> **When will this warning become a hard error?**
>
> Hopefully we will develop a finer-grained rule and this warning will never be an error.

We should revisit this when we're actually ready to release 0.7.0 and see what progress has been made on developing a finer-grained rule.

**Comment by joshlf** [comment]
@andrewpollack Are you still seeing this? I realized that, despite not having intentionally done anything about this, I've not seen this error emitted even in versions of the compiler after [the one you linked](https://github.com/rust-lang/rust/commit/83a28ef095ba4179a63196f16eadd97f110d6cb3).

**Comment by joshlf** [comment]
I'm gonna close this for now. Feel free to re-open if you are still seeing this.
