### ISSUE TITLE
Derive getters for ergonomics

### ISSUE THREAD

**Issue by gootorov** [google/zerocopy#152]
Consider the example in the `byteorder` module, specifically the `UdpPacket::src_port` getter:

```Rust
use zerocopy::{AsBytes, ByteSlice, FromBytes, LayoutVerified, Unaligned};
use zerocopy::byteorder::network_endian::U16;

#[derive(FromBytes, AsBytes, Unaligned)]
#[repr(C)]
struct UdpHeader {
    src_port: U16,
    dst_port: U16,
    length: U16,
    checksum: U16,
}

struct UdpPacket<B: ByteSlice> {
    header: LayoutVerified<B, UdpHeader>,
    body: B,
}

impl<B: ByteSlice> UdpPacket<B> {
    fn parse(bytes: B) -> Option<UdpPacket<B>> {
        let (header, body) = LayoutVerified::new_from_prefix(bytes)?;
        Some(UdpPacket { header, body })
    }

    fn src_port(&self) -> u16 {
        self.header.src_port.get()
    }

    // more getters...
}
```

I often find myself either writing getters like this one manually (which is boilerplate-y), or just making the field public and calling `.get()` everywhere (which doesn't look great).

In my opinion, if these getters were derive-able by an additional proc-macro, this could significantly improve the ergonomics of `zerocopy`. Do you think this library could provide such macro, or does this fall a bit out of scope? If the former, I could open a draft PR for further discussion.

**Comment by gootorov** [comment]
Sorry, I didn't notice `src_port` is a part of `UdpHeader`, not the `UdpPacket`, so I guess it's a bad example.

So, what I meant is, the hypothetical derive macro would provide getters for `src_port`, `dst_port`, `length`, and `checksum` on `UdpHeader`, where each getter would return a primitive type.

In the case of `UdpPacket`, it would generate a getter for the `header` , and the `body`.

I guess it is not straight-forward what to do with `[u8; X]` style of fields, but I hope that could be discussed and resolved.

**Comment by gootorov** [comment]
Another alternative could be to implement `Deref` for `byteorder` types, tough it is sometimes considered an anti-pattern for newtypes, and also calling `.get()` shows explicit cost, which now would be a bit hidden. One the plus side, it is certainly a lot less complexity than another derive macro.

Sorry if I'm making too much of a big deal out of this :)

**Comment by joshlf** [comment]
This feels a bit out of scope for zerocopy; I could imagine something like the following, which feels more natural to be in its own crate that doesn't have special knowledge of zerocopy:

```rust
#[derive(Getters)]
struct Foo {
    #[getter] // Assumes default name(s) for getter methods
    field1: A,
    #[getter(get_method)] // Use `get_method` instead of default name(s) for getter methods
    field2: B,
    field3: C,
}
```

You could imagine extensions for value/reference/mutable reference getters, getters which reach into sub-fields (like you do in your example with `self.header.src_port.get()`), etc. Could be a cool crate! Just seems out of scope for zerocopy.
