### ISSUE TITLE
Derive tests take too long to compile and run

### ISSUE THREAD

**Issue by djkoloski** [google/zerocopy#1582]
Running `cargo clean && cargo test -p zerocopy-derive` takes upwards of a 1m20s on my relatively beefy machine. Compiling `enum_from_bytes` alone makes up 89% of that time - a full 1m11s. By comparison, `cargo clean && cargo test -p zerocopy` only takes 12s. Additionally, actually compiling `zerocopy-derive` only takes around 2.3s.

General slowness also makes rust-analyzer lag pretty far behind and compete over the lockfile with any command-line operations. This results in a pretty miserable development experience.

**Comment by joshlf** [comment]
Is there any way to get `cargo test` to skip compiling a test by default? Analogous to `#[ignore]`, but for compilation rather than for running the test? If so, we could compile and run `enum_from_bytes` in CI but disable it by default for local development.
