### ISSUE TITLE
`Unalign` ABI promises are wrong

### ISSUE THREAD

**Issue by Nilstrieb** [google/zerocopy#164]
https://docs.rs/zerocopy/latest/zerocopy/struct.Unalign.html states

> `Unalign<T>` has the same size and ABI as `T`

This is wrong, as the type is `#[repr(C, packed)]` and not `repr(transparent)`.

The [Rust reference](https://doc.rust-lang.org/reference/type-layout.html#the-transparent-representation) about `repr(transparent)`:

> This is different than the C representation because a struct with the C representation will always have the ABI of a C struct while, for example, a struct with the transparent representation with a primitive field will have the ABI of the primitive field.

Here's an example of such an ABI mismatch in practice: https://godbolt.org/z/bhP71dnh4

The docs should be relaxed to not promise full ABI compatibility, but only promise what `repr(C)` promises (which is probably strong enough for most use cases).

**Comment by Lokathor** [comment]
Specifically, the memory layout will still be the same as that of the wrapped type, but the function calling convention can differ.

**Comment by chorman0773** [comment]
This seems like it should also affect any x86-64 Sys-V platform.

When determining the class of structures, 
> If the size of an object is larger than four eightbytes, or it contains unaligned
fields, it has class MEMORY.

**Comment by joshlf** [comment]
Good catch, thanks @Nilstrieb! Uploaded a fix [here](https://github.com/google/zerocopy/pull/168).
