### ISSUE TITLE
doc.rs points to defunct google repo, can we update to this one?

### ISSUE THREAD

**Issue by jasonsewall** [google/zerocopy#165]
https://docs.rs/zerocopy/0.6.1/zerocopy/ points to https://fuchsia.googlesource.com/fuchsia/+/HEAD/src/lib/zerocopy, which is a dead repo.

Is this the same project as that one? Is this the repo for it? Can we update the link to point to this?

It's both confusing and potential security issue for the docs.rs link to point to something incorrect.

**Comment by joshlf** [comment]
This is fixed in 0.7.0. [0.7.0-alpha](https://docs.rs/zerocopy/0.7.0-alpha/zerocopy/index.html) has already been released (along with a few subsequent alpha releases), but there is not yet a stable release of 0.7.0, and likely won't be for a while.

**Comment by joshlf** [comment]
Hey @jasonsewall, just wanted to let you know that we just released 0.6.2, which includes all of the non-breaking changes from 0.7.0, and also fixes this issue.
