### ISSUE TITLE
Implement `FromBytes` and `AsBytes` for raw pointers

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#170]
Historically, we've avoided adding these impls for fear that they could present a footgun, making it easier to accidentally transmute into a type, breaking its safety invariants.

Today, I was working on replacing some `unsafe` code in Fuchsia's Starnix project with zerocopy, and ran into some structs for which I can't derive `FromBytes` or `AsBytes` because they contain raw pointers. Currently, the lack of impls on raw pointers is entirely preventing this `unsafe` code from being replaced by zerocopy, which feels to me like throwing the baby out with the bathwater. IMO, it's more important to unlock this use case than to avoid a minor and theoretical footgun.

Note that, while the [layout of raw pointers is well-defined](https://doc.rust-lang.org/reference/type-layout.html#pointers-and-references-layout), it's less clear that their bit validity is well-defined.

TODO:
 - [ ] [Confirm that these impls would actually be sound](https://github.com/rust-lang/unsafe-code-guidelines/issues/401)
 - [ ] Resurrect [this PR](https://github.com/google/zerocopy/pull/171)

**Comment by joshlf** [comment]
@djkoloski Given the discussion in https://github.com/rust-lang/unsafe-code-guidelines/issues/401, how would you feel about just implementing `AsBytes` for now and leaving `FromBytes` for when we've had a deeper discussion about how much of a footgun we're comfortable introducing?

**Comment by CAD97** [comment]
I would lean towards treating `AsBytes`/`FromBytes` similar to `Send`/`Sync` here. Raw pointers on their own don't carry any safe API which would make `Send`/`Sync` implementations unsound. Rather, it's that their typical usage is typically not `Send`/`Sync` and should consider carefully before implementing those traits.

One could imagine a parallel world where raw pointers were `Send`/`Sync` and containers built on them need to contain some `PhantomLocal` marker to opt out of the autotraits, but that's not the particular tradeoff that was chosen here. Lacking some code required for soundness is also the worst and most subtle kind of soundness bug; typically soundness holes are introduced because of the presence of some `impl`, not the lack of one, precisely because raw pointers not being `Send`/`Sync` makes it difficult to write code reliant on the lack of an autotrait `impl` for soundness. (And `Unpin` not being `unsafe` to implement is often quoted as a footgun due to that exact reason of relying on the lack of an impl for soundness.)

The proof burden/overhead of writing `unsafe impl` for `FromBytes`/`AsBytes` for types holding raw pointers is IMHO appropriate; by doing so the type author is acknowledging the risks involved (e.g. can no longer encapsulate pointer validity).

The calculus is a bit different here since these are opt-in derivable traits rather than autotraits, but I'd say the same logic still applies. It should be fine to just derive all derivable traits without needing to consider whether `unsafe` elsewhere makes the derive incorrect.

**Comment by djkoloski** [comment]
I was under the impression that transmuting pointers to/from bytes was always sound, and that it was just dereferencing transmuted pointers which was unsound. I think that's maybe correct in practice but not entirely correct in theory?

@joshlf Could you point to an example type with pointers that you want to use zerocopy on? I think there is a lot of room for compromise, like a transparent wrapper type or a field attribute with the derive.

**Comment by digama0** [comment]
> I was under the impression that transmuting pointers to/from bytes was always sound, and that it was just dereferencing transmuted pointers which was unsound. I think that's maybe correct in practice but not entirely correct in theory?

As mentioned in the [linked issue](https://github.com/rust-lang/unsafe-code-guidelines/issues/401), this is basically correct, but even if so, the argument @CAD97 is making is that users might make the mistaken assumption (the docs are not clear on whether this is true or not) that transmuting something `FromBytes` and then back again via `AsBytes` is a lossless operation, resulting in a pointer which is as good as the original. If not, what is even the point of having the address value?

If you are okay with a wrapper type, I would suggest an `ExposedPtr<T>` type which is a wrapper around `*const T` with the invariant that it contains only pointers that have been "exposed" via as-casting to an integer. These can be safely round-tripped through raw bytes without losing their permissions to the original allocation.

**Comment by joshlf** [comment]
> @joshlf Could you point to an example type with pointers that you want to use zerocopy on? I think there is a lot of room for compromise, like a transparent wrapper type or a field attribute with the derive.

So I think I may have jumped the gun on this one. The original impetus for considering adding these impls was that I was doing a pass through Fuchsia's codebase, looking for `mem::transmute`s to replace with `zerocopy::transmute!`. I came across a few transmutes that would have required making a big tree of types `FromBytes` and `AsBytes`. In the haze of sifting through thousands of lines of code, I got the impression that there was a lot of code that could benefit from those impls.

However, when I went back now to answer your question, I looked through and found precisely two instances of `transmute` that could be replaced if only a raw pointer implemented `FromBytes` or `AsBytes`. I even made this fancy table because I was expecting to have a lot more data to report:

| Trait | Type | Needed (transitively) by |
|--------|--------|--------|
| `FromBytes` | [ucontext](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/starnix/lib/linux_uapi/src/x86_64.rs;l=4940;drc=0d5b319ef73799a2e0ff89465461cd0fb5dffed4) | [this transmute](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/starnix/kernel/arch/x64/signal_handling.rs;l=109;drc=ac3b82435b73cd091bff9d455d97969ac2caa804) (to replace it with `transmute!`)|
| `AsBytes` | [ucontext](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/starnix/lib/linux_uapi/src/x86_64.rs;l=4940;drc=0d5b319ef73799a2e0ff89465461cd0fb5dffed4) | [this transmute](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/starnix/kernel/arch/x64/signal_handling.rs;l=105;drc=ac3b82435b73cd091bff9d455d97969ac2caa804) (to replace it with `self.as_bytes() |

Now, that's only `transmute`, of which there are a few tens in Fuchsia's codebase (ignoring those generated by `bindgen`, which number in the hundreds). Fuchsia has in the neighborhood of 10,000 instances of `unsafe` more generally, so it's possible that, going through that code, I'd find a lot more. But right now, all I have to show concretely are those two instances.

**Comment by joshlf** [comment]
Follow up: Would it be sound to implement `FromZeroes` for raw pointer types? Are there any provenance concerns for null pointers? In other words, for `T: Sized`, is `transmute::<_, *const T>([0u8; size_of::<P>()]` sound?

cc @ralfjung since we've been talking about pointer validity and provenance

**Comment by digama0** [comment]
I can't think of any reason this would be problematic. I'm not sure if we document that 0 is the null pointer (I'm guessing we do), but it doesn't need to have provenance in any case.

**Comment by joshlf** [comment]
I assume that, despite fat pointers logically containing a thin pointer and a length, the actual layout/bit representation of fat pointers is not guaranteed by the reference, and so it would not be sound to implement `FromZeroes` for e.g. `*const [T]`?

**Comment by RalfJung** [comment]
Transmuting a `usize` to a thin raw pointer should always be sound, I see no reason why that would not work. The other direction is the problematic one.

(Note that the resulting pointer might be "even less valid than a `ptr::invalid` pointer", whatever that means. But as long as you never actually do anything with that raw pointer, it's fine.)

> I assume that, despite fat pointers logically containing a thin pointer and a length, the actual layout/bit representation of fat pointers is not guaranteed by the reference, and so it would not be sound to implement FromZeroes for e.g. *const [T]?

Layout of wide pointers is indeed undocumented, they may only be created via `ptr::from_raw_parts`. Note that transmuting a bunch of 0s to `*const dyn Trait` is insta-UB as of today, we even emit `nonnull` attributes to LLVM for the vtable (but we might change that in the future).

**Comment by joshlf** [comment]
Leaving a note here: if we implement [this Clippy lint](https://github.com/rust-lang/rust-clippy/issues/11734), then this may be less dangerous, since our `transmute!` macro desugars to `mem::transmute`. We'd need to make sure a similar lint would fire in other cases (e.g., today, `transmute_ref!` and `transmute_mut!` desugar to other functions, and there are also APIs other than these macros which effectively enable transmutation).

**Comment by joshlf** [comment]
Closing in favor of #1818
