### ISSUE TITLE
Expose the inner value of `Unalign` as public

### ISSUE THREAD

**Issue by kupiakos** [google/zerocopy#1860]
This enables full field reference projection for fields that are sufficiently aligned and field read/write access for all fields and subfields. This must be done through direct struct field access for the compiler to accept it.

## Sample use case

Say the input buffer you receive has bytes in the format of `BigStruct`, and our function reads specific fields out of those bytes based on a struct layout defined by bindgen. There are too many unread fields to reasonably copy it. However, the input buffer may be unaligned. So, you first access the prefix as a `&Unalign<BigStruct>`.

In order to access specific unaligned fields safely, you need one of the following:

- [Field projection](https://github.com/google/zerocopy/issues/196)
- To copy the whole struct
- To use `unsafe`
- Have field access to the contents of the `Unalign`.

Currently, the workaround is to declare your own `repr(packed)` newtype that has an accessible inner value. But honestly, I should be able to use the built-in `Unalign` newtype for this. Rust will guard against an accidental reference to an unaligned field.

**Comment by kupiakos** [comment]
It might be worth gating the inner `pub` field based on Rust version since the lint producing a hard error for referencing an underaligned field was [introduced in 1.69](https://doc.rust-lang.org/stable/releases.html#compatibility-notes-11).

Additionally, if we add `T: ?Sized` to `Unalign`, then [only in 1.76](https://doc.rust-lang.org/stable/releases.html#version-1760-2024-02-08) was this lint fixed for unsized fields.

**Comment by joshlf** [comment]
Merging this into https://github.com/google/zerocopy/issues/836#issuecomment-2499221898
