### ISSUE TITLE
is it possible to opt out of safety guarantees

### ISSUE THREAD

**Issue by Freax13** [google/zerocopy#1919]
Is there a way to use unsafe code to opt out of the safety guarantees and *pretend* that a type implements the marker traits (e.g. `IntoBytes` and `Immutable`)? I'm trying to implement a trait with an unsafe method that receives a generic value `T` and would like to use that value with my existing code that already makes use of `IntoBytes` and `Immutable`. I know that `T` could in theory implement those traits (it's part of the safety requirements for the trait method), but the trait interface is declared in another crate out of my control, so I can't just add the bound to the trait interface.

It'd be nice if it was possible to implement a wrapper type and manually implement the marker traits on the wrapper, but AFAICT this is very strongly discouraged.

**Comment by joshlf** [comment]
Can you point us to the code you'd hope to use this with? It is difficult to support in the general case because our traits have `#[doc(hidden)]` items that are a) not semver stable and b) sometimes need to be synthesized based on the AST (we do this in our derives). But maybe we could support your specific use case.

**Comment by Freax13** [comment]
It'd look something like this:
```rust
use external::Foo;
use zerocopy::{Immutable, IntoBytes};

mod external {
    //! This is code in another crate that I can't change.

    pub trait Foo {
        /// # Safety
        ///
        /// `T` satifies all the requirements of `Immutable` and `IntoBytes`.
        unsafe fn bar<T>(value: &T);
    }
}

struct Baz;

impl Foo for Baz {
    unsafe fn bar<T>(value: &T) {
        my_important_business_logic(value); // <-- This doesn't work :(
    }
}

/// This is the existing code I'm already using in other places and that I'd
/// like to use in `<Baz as Foo>::bar`.
fn my_important_business_logic<T>(value: &T)
where
    T: IntoBytes + Immutable,
{
    for b in value.as_bytes() {
        println!("{b:02x}");
    }
}
```

My hope was that there could be some unsafe way of pretending that `T` implements `IntoBytes + Immutable` that I could use in `<Baz as Foo>::bar`.

**Comment by osteffenrh** [comment]
So something like this?

```rust
use external::Foo;
use zerocopy::{Immutable, IntoBytes};

mod external {
    //! This is code in another crate that I can't change.

    pub trait Foo {
        /// # Safety
        ///
        /// `T` satifies all the requirements of `Immutable` and `IntoBytes`.
        unsafe fn bar<T>(value: &T);
    }
}

struct Baz;

impl Foo for Baz {
    unsafe fn bar<T>(value: &T) {
        use core::{mem, slice};

        /// Wrapper that adds IntoBytes and Immutable to types
        /// that don't implement those themselves.
        /// This workaround is unsupported by the zerocopy crate
        /// and might break at any time!
        struct Wrapper<'a, T>(&'a T);

        /// SAFETY: This wrapper is only used within this implementation
        /// of `Baz::bar` and only on types specific to its usecase.
        unsafe impl<'a, T: Sized> IntoBytes for Wrapper<'a, T> {
            fn only_derive_is_allowed_to_implement_this_trait()
            where
                Self: Sized,
            {
            }

            fn as_bytes(&self) -> &[u8]
            where
                T: Sized,
            {
                let len = mem::size_of_val(self.0);
                let slf: *const T = self.0;
                unsafe { slice::from_raw_parts(slf.cast::<u8>(), len) }
            }
        }

        /// SAFETY: This wrapper is only used within this implementation
        /// of `Baz::bar` and only on types specific to its usecase.
        unsafe impl<'a, T: Sized> Immutable for Wrapper<'a, T> {
            fn only_derive_is_allowed_to_implement_this_trait()
            where
                Self: Sized,
            {
            }
        }

        my_important_business_logic(&Wrapper(value));
    }
}

/// This is the existing code I'm already using in other places and that I'd
/// like to use in `<Baz as Foo>::bar`.
fn my_important_business_logic<T>(value: &T)
where
    T: IntoBytes + Immutable,
{
    for b in value.as_bytes() {
        println!("{b:02x}");
    }
}

fn main() {
    unsafe {
        let data = 0xdeadbeefu32;
        Baz::bar(&data);
    }
}
```

**Comment by Freax13** [comment]
@joshlf thanks for clarifying!

> So something like this?
> 
> ```rust
> use external::Foo;
> use zerocopy::{Immutable, IntoBytes};
> 
> mod external {
>     //! This is code in another crate that I can't change.
> 
>     pub trait Foo {
>         /// # Safety
>         ///
>         /// `T` satifies all the requirements of `Immutable` and `IntoBytes`.
>         unsafe fn bar<T>(value: &T);
>     }
> }
> 
> struct Baz;
> 
> impl Foo for Baz {
>     unsafe fn bar<T>(value: &T) {
>         use core::{mem, slice};
> 
>         /// Wrapper that adds IntoBytes and Immutable to types
>         /// that don't implement those themselves.
>         /// This workaround is unsupported by the zerocopy crate
>         /// and might break at any time!
>         struct Wrapper<'a, T>(&'a T);
> 
>         /// SAFETY: This wrapper is only used within this implementation
>         /// of `Baz::bar` and only on types specific to its usecase.
>         unsafe impl<'a, T: Sized> IntoBytes for Wrapper<'a, T> {
>             fn only_derive_is_allowed_to_implement_this_trait()
>             where
>                 Self: Sized,
>             {
>             }
> 
>             fn as_bytes(&self) -> &[u8]
>             where
>                 T: Sized,
>             {
>                 let len = mem::size_of_val(self.0);
>                 let slf: *const T = self.0;
>                 unsafe { slice::from_raw_parts(slf.cast::<u8>(), len) }
>             }
>         }
> 
>         /// SAFETY: This wrapper is only used within this implementation
>         /// of `Baz::bar` and only on types specific to its usecase.
>         unsafe impl<'a, T: Sized> Immutable for Wrapper<'a, T> {
>             fn only_derive_is_allowed_to_implement_this_trait()
>             where
>                 Self: Sized,
>             {
>             }
>         }
> 
>         my_important_business_logic(&Wrapper(value));
>     }
> }
> 
> /// This is the existing code I'm already using in other places and that I'd
> /// like to use in `<Baz as Foo>::bar`.
> fn my_important_business_logic<T>(value: &T)
> where
>     T: IntoBytes + Immutable,
> {
>     for b in value.as_bytes() {
>         println!("{b:02x}");
>     }
> }
> 
> fn main() {
>     unsafe {
>         let data = 0xdeadbeefu32;
>         Baz::bar(&data);
>     }
> }
> ```

We don't need to explicitly implement `as_bytes` (there's already a provided default implementation), but yeah. I'm not a huge fan of implementing `only_derive_is_allowed_to_implement_this_trait` ourselves, but I'm fine with trying this out to see if this actually causes problems in the future.

**Comment by joshlf** [comment]
Yep that's exactly it. Let us know if you have any issues with it in the future!
