### ISSUE TITLE
README is missing from zerocopy's page on crates.io

### ISSUE THREAD

**Issue by tim-seoss** [google/zerocopy#193]
Whilst there is a README.md in the root of the project's git repository, https://crates.io/crates/zerocopy says:

"zerocopy v0.6.1 appears to have no README.md file"

**Comment by joshlf** [comment]
That's right - we only added a README after releasing 0.6.1. The README is present in [0.7.0-alpha](https://crates.io/crates/zerocopy/0.7.0-alpha) and later versions.

**Comment by joshlf** [comment]
Hey @tim-seoss, just wanted to let you know that we just released 0.6.2, which includes all of the non-breaking changes from 0.7.0, and also fixes this issue.
