### ISSUE TITLE
`write_to_prefix` (and similar ones) take ownership of the buffer

### ISSUE THREAD

**Issue by SuperKenVery** [google/zerocopy#195]
Please correct me if I'm wrong, but by taking ownership of the buffer, it seems to release the buffer as soon as the function exits, and subsequent code cannot use the buffer. 

The method is defined as follows:

```rust
    /// Writes a copy of `self` to the prefix of `bytes`.
    ///
    /// `write_to_prefix` writes `self` to the first `size_of_val(self)` bytes
    /// of `bytes`. If `bytes.len() < size_of_val(self)`, it returns `None`.
    fn write_to_prefix<B: ByteSliceMut>(&self, mut bytes: B) -> Option<()> {
        let size = mem::size_of_val(self);
        if bytes.len() < size {
            return None;
        }

        bytes[..size].copy_from_slice(self.as_bytes());
        Some(())
    }
```

I think the method should only borrow the buffer. 

Again, correct me if I'm wrong please!

**Comment by joshlf** [comment]
If your `B` type is `&mut [u8]`, you can reborrow [like this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a09ebedf1a20714f577b5a7d2e329280). That said, `ByteSliceMut` is also implemented for [`RefMut`](https://doc.rust-lang.org/nightly/core/cell/struct.RefMut.html), so your suggestion is still a good one! I'll consider changing the signature of this and other methods/functions.

**Comment by joshlf** [comment]
This was fixed in https://github.com/google/zerocopy/pull/204.
