### ISSUE TITLE
`nightly-float` feature for `f16` and `f128`

### ISSUE THREAD

**Issue by tgross35** [google/zerocopy#1999]
Rust has the unstable [`f16`](https://doc.rust-lang.org/std/primitive.f16.html) and [`f128`](https://doc.rust-lang.org/nightly/std/primitive.f128.html) features. Would it be possible to support these under a new `nightly-float` flag?

**Comment by joshlf** [comment]
We'd be open to supporting this! Feel free to put up a PR to the v0.8.x branch. If you don't want to do it yourself, we can also do it - we just can't give any guarantees about when we'll have time to implement this.

**Comment by joshlf** [comment]
Closed by #2042, published in [0.8.10](https://crates.io/crates/zerocopy/0.8.10).

**Comment by tgross35** [comment]
Oh awesome, somebody beat me to it. Thanks!
