### ISSUE TITLE
Unnecessary `Fn` bound for `SizeError::map_src`.

### ISSUE THREAD

**Issue by conradludgate** [google/zerocopy#2009]
I am implementing a small wrapper over `read_from_bytes` that allows working over types like `Bytes` instead of `&[u8]`. As such I want to change the `Src` bound to be `Bytes` instead of `&[u8]`.

However, the bound on `map_src` is unnecessarily a `Fn(Src) -> NewSrc` which implies it would be callable multiple times. This is inconsistent with other forms of `map` which use `FnOnce`. This is a problem for me as I cannot simply `map_src(|_| bytes_buf)` as that moves ownership, giving me the error

```rust
error[E0507]: cannot move out of `buf`, a captured variable in an `Fn` closure
   --> proxy/src/protocol2.rs:371:40
    |
363 |         let buf = if self.len() < len {
    |             --- captured outer variable
...
371 |         res.map_err(|e| e.map_src(|()| buf))
    |                                   ---- ^^^ move occurs because `buf` has type `bytes::BytesMut`, which does not implement the `Copy` trait
    |                                   |
    |                                   captured by this `Fn` closure
    |
help: consider cloning the value if the performance cost is acceptable
    |
371 |         res.map_err(|e| e.map_src(|()| buf.clone()))
    |                                           ++++++++
```

Easy to fix here with a clone, sure. But it's not ideal.

I have a feeling this can be fixed without a breaking change, but I'm not 100% certain.

**Comment by joshlf** [comment]
This is fixed in [0.8.9](https://crates.io/crates/zerocopy/0.8.9).
