### ISSUE TITLE
Create GitHub Action to automatically back-port PRs between branches

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#2014]
For example, #1997 was originally submitted against `v0.8.x` and merged as https://github.com/google/zerocopy/commit/dc537e7ca058f4f7e31473b982ceab38514dab61. It was then manually backported to `main` in #2013.

Instead, we'd like to have a GitHub Action that we can manually trigger from the GitHub web UI that will create a new PR from the commit resulting from the old PR (in the above example, https://github.com/google/zerocopy/commit/dc537e7ca058f4f7e31473b982ceab38514dab61). This action will need to take:
- The commit hash to back-port
- The target branch for the new PR

It should be possible to adapt our existing [release-crate-version.yml](https://github.com/google/zerocopy/blob/255babe875f371a6e2a9e01c258ce5ebc54bd6bb/.github/workflows/release-crate-version.yml) workflow.

**Comment by joshlf** [comment]
@Aditya-PS-05 , since you're interested in contributing, I wanted to bring this to your attention in case you're interested.

**Comment by Aditya-PS-05** [comment]
@joshlf , 
Thanks for considering me. 
Yeah, please assign me this issue. I will try to resolve it.

**Comment by joshlf** [comment]
Awesome, assigned!
