### ISSUE TITLE
Document that derive macros create impls for multiple traits

### ISSUE THREAD

**Issue by lolbinarycat** [google/zerocopy#2037]
`FromBytes` adds and impl for `FromZeros` and `TryFromBytes`, while `FromZeros` adds an impl for `TryFromBytes`.

this does not match the typical behavior of derives, where not even supertraits are derived automatically (thus why you have to separately derive `Clone` and `Copy`).

this behavior is not documented.

**Comment by jswrenn** [comment]
I opened a PR to document this behavior: https://github.com/google/zerocopy/pull/2038

**Comment by joshlf** [comment]
Closed in #2038.
