### ISSUE TITLE
On RustRover Trait `Immutable` is not implemented for `U64<BigEndian>` [E0277]

### ISSUE THREAD

**Issue by boranby** [google/zerocopy#2092]
Hi,
I see `Trait 'Immutable' is not implemented for 'U64<BigEndian>' [E0277]`. It happens for all `I32<BigEndian>, U16<BigEndian>, U32<BigEndian> etc.` when I use `as_bytes()` for my struct.

An example struct and it's derives.
```rust
#[derive(IntoBytes, KnownLayout, Immutable, FromBytes, Builder, Getters, Debug, Eq, PartialEq, Clone, Copy)]
#[repr(C, packed)]
pub struct OrderMessage {
    quantity: U64<BigEndian>,
    price: I32<BigEndian>,
}
``` 

It compiles successfully but I see that in RustRover.
![Image](https://github.com/user-attachments/assets/6a950929-08dc-42d7-817c-0d446f08570f)

**Comment by boranby** [comment]
I just migrated from 0.7.35 to 0.8.10. Please let me know, if I do something wrong.

**Comment by joshlf** [comment]
Since it compiles successfully, this sounds like a RustRover bug. I'd recommend filing a bug with them first, but feel free to follow up here if it turns out that it's actually a zerocopy bug.
