### ISSUE TITLE
Tag, branch releases

### ISSUE THREAD

**Issue by jcajka** [google/zerocopy#214]
IMHO it would be great if there would be tagged/branched releases for each respective release(of crate). Currently it is hard to track release back to the commit.

**Comment by joshlf** [comment]
Just tagged all of the release commits: https://github.com/google/zerocopy/tags

Note that we used to not keep zerocopy's and zerocopy-derive's version numbers in lock-step, so there are some tags with a `derive-` prefix. We won't add those going forward now that they're in lock step.
