### ISSUE TITLE
vec![...;. ..]-like macro for "late" allocation

### ISSUE THREAD

**Issue by peter-lyons-kehl** [google/zerocopy#2185]
Problem: x64 standard Linux, with VM overcommit (as is default), and no large transparent pages, supports zeroed "delayed" allocation/late assignment of physical pages on demand. But it seems to do so only for `vec![0; len]` macro and only for numeric types ([stackoverflow #71946484](https://stackoverflow.com/questions/71946484/why-is-vec0-super-large-number-so-memory-efficient-when-the-default-value)).

Of course,
- https://github.com/google/zerocopy/blob/main/src/lib.rs#L2954-L2956 reads only that "On systems that..., using `new_box_zeroed` (or related functions) may have performance benefits." It does not give any guarantee.
- You don't want to dance around/jump as Linux, or any platform/target, whistles.

Yet, Linux is a major platform. And using this would be a major benefit.

Suggest a macro-by-example `vec_zeroed![type; len]`, with semantics similar to standard `vec![value; len]`. It would
- choose a relevant primitive (`u8/u16/u32...`) based on the type's alignment
- calculate the size of the relevant primitive alternative vector
- allocate it with `vec!` and `transmute`.

See the definition https://github.com/peter-lyons-kehl/zerocopy-vec/blob/main/src/lib.rs#L61 and its test https://github.com/peter-lyons-kehl/zerocopy-vec/blob/main/src/lib.rs#L193.

If you'd like to absorb it, I'm happy to create a pull request. If this needs any formal validation, point me to docs/examples...

An alternative is to derive `Default`, and then use either `vec![Default::default(); len]` or `vec![S::default();  len]`. However, that would restrict use/compatibility with 3rd party types. (See https://github.com/peter-lyons-kehl/zerocopy-vec/blob/main/src/lib.rs#L215.)

Opinions, tips...?

**Comment by jswrenn** [comment]
Hi Peter, thanks for the issue!

> Problem: x64 standard Linux, with VM overcommit (as is default), and no large transparent pages, supports zeroed "delayed" allocation/late assignment of physical pages on demand. But it seems to do so only for `vec![0; len]` macro and only for numeric types ([stackoverflow #71946484](https://stackoverflow.com/questions/71946484/why-is-vec0-super-large-number-so-memory-efficient-when-the-default-value)).

Are you sure that `new_vec_zeroed` doesn't share this behavior? As the stackoverflow answer points out, `vec![0; len]` achieves this feat by calling `alloc_zeroed` — which is exactly what `new_box_zeroed` does. However, just like `vec` we cannot *guarantee* any special allocator, since the application can always change out the global allocator.

**Comment by peter-lyons-kehl** [comment]
Hi Jack,

My mistake. All fine.
Thank you.
