### ISSUE TITLE
Enable GitHub merge queue

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#344]
[Enable the Github merge queue](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/#get-started-now-with-merge-queue). Merge queues prevent [semantic conflicts](https://bors.tech/essay/2017/02/02/pitch/), thus providing an additional safeguard against breaking the main branch.

**Comment by joshlf** [comment]
Woah, didn't know about this! Absolutely.

Looks like we need to [update our CI](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) to support it first:

<img width="755" alt="Screenshot 2023-09-07 at 9 18 59 AM" src="https://github.com/google/zerocopy/assets/1046063/a04640d8-d723-4de2-9978-8b8ae042762e">

Feel free to put up a PR. If not, I'll take a stab at this at some point.
