### ISSUE TITLE
Remove deprecated *.out and *.err files

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#36]
In `zerocopy-derive/tests/ui`, we have `*.out` and `*.err` files that are holdovers from when we used [`compiletest_rs`](https://crates.io/crates/compiletest_rs) instead of [`trybuild`](https://crates.io/crates/trybuild) for our UI tests. They don't do anything and should be removed.

**Comment by SanchithHegde** [comment]
I'll take this up.
