### ISSUE TITLE
Replace for loop with `[u8]::fill` method

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#38]
In `map_zeroed` and `map_prefix_tuple_zeroed`, we zero a byte slice by doing:

```rust
for b in lv.0.iter_mut() {
    *b = 0;
}
```

Instead, we could use [`[u8]::fill`](https://doc.rust-lang.org/std/primitive.slice.html#method.fill):

```rust
lv.0.fill(0);
```

**Comment by MSalah73** [comment]
I'll take this one

**Comment by joshlf** [comment]
Awesome, thanks @MSalah73! Welcome to zerocopy 😃
