### ISSUE TITLE
Use `kani-github-action` for Kani in CI.

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#423]
Replace our hand-rolled Kani CI job:
https://github.com/google/zerocopy/blob/3bb9a54ff458e104f7eb24beda7f8fb09794e1a5/.github/workflows/ci.yml#L229-L250
...with the official Kani github action: https://model-checking.github.io/kani/install-github-ci.html

**Comment by Agnik7** [comment]
Hi! I am participating in Hacktoberfest and would love to work on this issue!
Could you kindly tell me which branch to work on?

**Comment by Agnik7** [comment]
@joshlf thanks, got it!!

**Comment by Agnik7** [comment]
@joshlf I have created a PR #472 to address this issue. Requesting your review to the PR.
