### ISSUE TITLE
Add comment to README.md stating that it's auto-generated and shouldn't be edited directly

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#45]
Update `generate-readme.sh` to emit a comment following the copyright comment that explains that:
- `README.md` is generated automatically
- Edits should be made in the doc comment on `src/lib.rs` or in `generate-readme.sh`

**Comment by Varad0124** [comment]
Can assign ths task to me ?

**Comment by joshlf** [comment]
Done!
