### ISSUE TITLE
Test Clippy in CI

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#49]
Exactly what it says on the tin.

@frazar is working on this in #51

**Comment by joshlf** [comment]
@frazar, if you leave a comment here, then I can assign this to you. Otherwise, it won't let me.

**Comment by frazar** [comment]
Sure thing! I'll be working towards closing this issue

**Comment by joshlf** [comment]
Hahaha you know what I just realized? That PR only runs Clippy on zerocopy, but not on zerocopy-derive. Mind putting up another one for zerocopy-derive? It's just the exact same thing, but with an extra `--manifest-path` argument. E.g.:

https://github.com/google/zerocopy/blob/e5e9b1fa05933750db526a489f73050032c5eb70/.github/workflows/ci.yml#L90-L91

**Comment by frazar** [comment]
Sure!
