### ISSUE TITLE
Add `transmute_mut` macro

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#490]
Our `transmute_ref` macro does not support transmuting between mutable reference types. To verify a transmutation from mutable reference to mutable reference, we must prove not only that the destination is valid for all possible source values, but also that the source is possible for all destination values. For instance:
```rust
let mut x = NonZeroU8::new(42).unwrap();
{
    let y : &mut u8 = transmute_mut!(&mut x); // UNSOUND!
    *y = 0; // `x` is no long valid
}

let z : NonZeroU8 = x;
```
The above transmutation is invalid, because constructing a `&mut u8` from a `&mut NonZeroU8` can be used to violate the validity invariants of the underlying `NonZeroU8`. It's not valid to transmute from `u8` into `NonZeroU8`.

**Comment by joshlf** [comment]
Closed in https://github.com/google/zerocopy/pull/550.
