### ISSUE TITLE
Deny other Clippy lints?

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#50]
Currently, we deny `clippy::indexing_slicing`. Should we deny others? So far, I've found:
- [`arithmetic_side_effects`](https://rust-lang.github.io/rust-clippy/master/#arithmetic_side_effects)
- [`alloc_instead_of_core`](https://rust-lang.github.io/rust-clippy/master/#alloc_instead_of_core)
- [`std_instead_of_core`](https://rust-lang.github.io/rust-clippy/master/#std_instead_of_core)

The `time` crate [has a good list](https://github.com/time-rs/time/blob/599a69ce35c43c7309a75ea2bb124f880bf0284a/time/src/lib.rs#L87).

We're tracking [`undocumented_unsafe_blocks`](https://rust-lang.github.io/rust-clippy/master/#undocumented_unsafe_blocks) separately in #61 since it will likely be a substantial change on its own.

**Comment by AntoniosBarotsis** [comment]
I know this is closed but in case you are not aware, you can also put all your lints in a cargo config file so that they are grouped together and not in your source code.

I am doing that in a project I am working on [here](https://github.com/AntoniosBarotsis/Rss2Email/blob/master/.cargo/config.toml) in case you are interested. Perhaps you know this already, just making sure!

**Comment by joshlf** [comment]
Oh interesting. What's the advantage of doing that over doing it in source code?

**Comment by AntoniosBarotsis** [comment]
In my case, back when I was using macros in my source code, I found some weird cases where the lints would not work properly between my main and my lib files. Other than that, it's just a bit easier to manage IMO but definitely not a big deal 👍

**Comment by joshlf** [comment]
Oh gotcha. Good to know about! Not sure we need it now, but I could see a future in which we want to synchronize across, e.g., zerocopy and zerocopy-derive, or across library code and code in `tests/`, etc.

**Comment by joshlf** [comment]
@AntoniosBarotsis in case you hadn't seen this, I just stumbled across the existence of [cargo.toml files](https://github.com/rust-lang/rust-clippy#configure-the-behavior-of-some-lints).

**Comment by joshlf** [comment]
Hahaha yes I did.
