### ISSUE TITLE
Use -Z randomize-layout

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#56]
When we're testing with the nightly toolchain in CI, we should use the [`-Z randomize-layout`](https://github.com/rust-lang/compiler-team/issues/457) rustc flag.

**Comment by itsyaasir** [comment]
Hey there, I would like to take up this issue. 
Thank you

**Comment by joshlf** [comment]
Awesome, thanks @itsyaasir ! Welcome to zerocopy 😃

**Comment by itsyaasir** [comment]
> Awesome, thanks @itsyaasir ! Welcome to zerocopy 😃

Thank you @joshlf
