### ISSUE TITLE
Don't deny warnings in UI tests

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#560]
As of #548, `cargo.sh` forwards `RUSTFLAGS` from the ambient environment to `cargo`. In CI, one such set flag is `-Dwarnings`, which elevates all warnings to errors. This impacts our UI tests: things which are, really, warnings, appear to be errors. Since the purpose of our UI tests is to confirm that compile errors are produced as expected on invalid code, this could lull us into a false sense of security if an "error" is really a warning.

Less pressingly, it currently means that all local trybuild runs during development need to be preceded by `RUSTFLAGS="-Dwarnings"` in order for the `.stderr` files to match in CI.

We need to prevent `RUSTFLAGS` from modifying lint levels when running UI tests. Ideally, this takes the form of porting to the `ui-test` crate, which I believe doesn't have this problem. See https://github.com/google/zerocopy/issues/187.

**Comment by joshlf** [comment]
@jswrenn Was this fixed by #567?
