### ISSUE TITLE
Add FromBytes/AsBytes/FromZeros derive support for unions?

### ISSUE THREAD

**Issue by newpavlov** [google/zerocopy#594]
Right now the derive macros do not work for unions and since they are the only allowed way of implementing the traits, it makes it impossible to use structs with unions together with the traits.

Is there anything preventing union support?

**Comment by joshlf** [comment]
Unions are supported:
* https://github.com/google/zerocopy/blob/main/zerocopy-derive/tests/union_as_bytes.rs
* https://github.com/google/zerocopy/blob/main/zerocopy-derive/tests/union_from_bytes.rs
* https://github.com/google/zerocopy/blob/main/zerocopy-derive/tests/union_from_zeroes.rs

Is there a specific code snippet you tried that didn't work? It might be that the specific union you tried isn't supported for some reason (and it would not at all surprise me if our error messages are bad and made it seem like we just don't support unions full-stop).

**Comment by newpavlov** [comment]
The following code does not work:
```
#[derive(FromBytes, AsBytes)]
pub union Foo {
    a: u64,
    b: [u32; 2],
}
```

Am I doing something wrong?

**Comment by newpavlov** [comment]
Ah, sorry. The following code works:
```rust
#[derive(FromBytes, FromZeroes, AsBytes)]
#[repr(C)]
struct Foo {
    a: u32,
    b: u32,
}

#[derive(FromBytes, FromZeroes, AsBytes)]
#[repr(C)]
struct Bar {
    a: u64,
}

#[derive(FromBytes, FromZeroes, AsBytes)]
#[repr(C)]
pub union FooBar {
    foo: ManuallyDrop<Foo>,
    bar: ManuallyDrop<Bar>,
}
```
