### ISSUE TITLE
impl Clone + Copy for Ref

### ISSUE THREAD

**Issue by nathan** [google/zerocopy#627]
Since `Ref` is [essentially a reference type](https://github.com/google/zerocopy/issues/68), it would be nice if it implemented `Clone` and `Copy` when the underlying `ByteSlice` does. The whole point of `zerocopy` is *not* copying, so I imagine `clone`ing the entire underlying type through the `Deref` impl (which this would interfere with) is not a common operation.

My use case: I followed the [example](https://docs.rs/zerocopy/0.7.26/zerocopy/byteorder/index.html#example) for parsing a UDP header, so my structs look like this:

```rust
struct Header<B: ByteSlice> {
    pub props: Ref<B, Props>,
    pub names: B,
    pub name_hashes: B,
    pub package_ids: Ref<B, [PackageId]>,
// …
}
```

I can't take `&self`, do some processing on a `Ref`, and hand out types with the same lifetime as the underlying slice. But I can't take `self` either, because I do this for more than one field and `Ref: !Clone`, so my struct is `!Clone` too. I'd like to do something like this:

```rust
fn cool_packages<'a>(&self) -> impl 'a + Iterator<Item = &'a PackageId> where B: 'a + Clone {
    self.package_ids.clone()
        .into_slice()
        .iter()
        .filter(|p| is_cool(p))
}
```

Am I missing a soundness issue?

**Comment by joshlf** [comment]
This should be doable; I'll put it on our roadmap for 0.8.
