### ISSUE TITLE
Add some examples on how to use the structs deriving the traits

### ISSUE THREAD

**Issue by OscarTHZhang** [google/zerocopy#630]
Currently there is no concrete examples in the official doc. It'd be good to add some simple examples (either in the doc or in this repo) to show the users how to use the the derived trait features.

**Comment by joshlf** [comment]
Thanks for submitting this! It's an issue we're aware of, and it's tracked in https://github.com/google/zerocopy/issues/32. I'm going to close this in favor of that issue.

That said, if you have any specific types of example usages you're interested in, let me know and I can make sure we keep track of them!
