### ISSUE TITLE
Allocation failures are not panics

### ISSUE THREAD

**Issue by Darksonn** [google/zerocopy#651]
This is a documentation bug report. I've noticed that functions sometimes include a section like the following:

> # Panics
>
> Panics if `Vec::reserve(additional)` fails to reserve enough memory.

Allocation failures are handled by just calling into `vec.reserve`. However, the `reserve` method does not panic on allocation failure. Instead, it calls `abort`.

**Comment by joshlf** [comment]
Looks like `vec.reserve` bottoms out in [`handle_alloc_error`](https://doc.rust-lang.org/std/alloc/fn.handle_alloc_error.html), which may panic or abort depending on how the binary was built. Maybe this should say:

> If `Vec::reserve(additional)` fails to reserve enough memory, `extend_vec_zeroed` may panic or abort depending on how the program is configured to handle allocation failure.

**Comment by joshlf** [comment]
Closed by #1478
