### ISSUE TITLE
Rename `LayoutVerified` to `Ref`

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#68]
The `LayoutVerified` type wraps a byte slice reference. It is a witness type that guarantees that the length and alignment have been validated to be compatible with a type parameter, `T`. It's named based on this witness role (the layout has been "verified"), but the name is confusing for consumers. We should rename it to `Ref` or similar - it's a reference type that enables zero-copy operations, hence `zerocopy::Ref`.

**Comment by MSalah73** [comment]
I'll take this one

**Comment by joshlf** [comment]
Hi @MSalah73 , this one isn't ready for contribution yet unfortunately - I'm going to need to go through and make sure that this change doesn't break anything in Fuchsia. Once I've done that, I'll add the https://github.com/google/zerocopy/labels/Hacktoberfest or https://github.com/google/zerocopy/labels/experience-easy labels. In the meantime, check out those labels or the https://github.com/google/zerocopy/labels/experience-medium or https://github.com/google/zerocopy/labels/experience-hard labels for stuff that we need help with!
