### ISSUE TITLE
Make it easier to run CI tests locally

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#69]
We currently run a large suite of tests in CI, which includes testing with different tools across different toolchains and different targets. It also involves miscellaneous things like confirming that `README.md` is up to date, that code is properly formatted with `rustfmt`, etc. In other words, it's not as simple as just running `cargo test`.

As a result, it's easy to make changes that appear fine locally but break CI, requiring an edit-commit-push cycle just to see if all of the CI tests will pass. We should make it easier to run most or all of these tests locally. For especially fast tests (like `README.md` and code formatting), we could even provide them as commit hooks.

@djkoloski also reports finding this to be painful (https://github.com/google/zerocopy/issues/69#issuecomment-1304693936):

> I struggled specifically with formatting and forgetting to make stderr match in tests. Adding a way to format test files and an easier way to update all the stderr files for tests might be helpful. 🙂

The challenge here is going to be making these tests available without either a) moving everything out of our `ci.yml` and into a script (which means we don't get nice job output and error messages) or, b) duplicating everything (which is brittle).

**Comment by AntoniosBarotsis** [comment]
You could also look into something like [Toast](https://github.com/stepchowfun/toast).

**Comment by memark** [comment]
Some interesting tools in this space are
- [`act`](https://github.com/nektos/act)
- [`earthly.dev`](https://earthly.dev)

**Comment by AntoniosBarotsis** [comment]
One thing to keep in mind is that Act and I think Toast as well don't support Windows images (or at least didn't last time I tried IIRC).

**Comment by djkoloski** [comment]
I struggled specifically with formatting and forgetting to make stderr match in tests. Adding a way to format test files and an easier way to update all the stderr files for tests might be helpful. 🙂

**Comment by joshlf** [comment]
Awesome, added that to the issue description. This'll definitely be important to solve moving forward.

**Comment by joshlf** [comment]
@djkoloski I took a stab at pulling the scripts out of `ci.yml` and into a shell script [here](https://github.com/google/zerocopy/compare/main...test-scripts#diff-5ebe12a1851cda0190cf2ed6fcf42049b071c8eeaa9c495dc20b0adab7b1f773). There's still work to be done, but I probably won't get it to a state where I can merge for a few days, so I figured I'd send you that in case you want to just keep a copy of it locally until I get it merged.

**Comment by joshlf** [comment]
@djkoloski do you feel like https://github.com/google/zerocopy/pull/728 and https://github.com/google/zerocopy/pull/1171 combined are sufficient to close this issue?

**Comment by djkoloski** [comment]
Yes, this issue can be closed.
