### ISSUE TITLE
Distinguish between MSRV and minimum *working* Rust version

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#807]
With #791, we have the opportunity to decrease our MSRV to as low as 1.58. For 0.8's initial release, we should not target an MSRV this low. Our [current policy](https://github.com/google/zerocopy/blob/100ba98de68f577d7d2bfa2da4fc9492272ebf00/POLICIES.md#msrv) is to treat MSRV increases as a breaking changes. Since breaking changes should be infrequent, we should be careful not to back ourselves into a corner where our MSRV blocks us from providing vital functionality in a timely fashion.

Nonetheless, we should still strive for zerocopy to work on old as a Rust version as possible. To facilitate this, I propose that we distinguish between MSRV and Minimum Working Rust Version (MWRV). Our MSRV, encoded in the `rust-version` field of our `Cargo.toml` should remain at ~1.60 and decremented cautiously. Our MWRV, encoded `package.metadata.ci` in `Cargo.toml` should be as low as technically possible at all times. We should modify our CI to test on MWRV, instead of MSRV, and additionally check that MWRV <= MSRV.

**Comment by joshlf** [comment]
Reopening per #811.
