### ISSUE TITLE
How deal with String with zerocopy?

### ISSUE THREAD

**Issue by inevity** [google/zerocopy#837]
For AsBytes macro, the String type is not supported. So how workaroud this?
Use ffi Cstring? or something else?
I have some structure which have field other the example zeorcopy support, So how should workaround all those types and just use the zerocopy crate.

**Comment by joshlf** [comment]
Can you show me a code snippet that you're hoping would work? We can't do `String: AsBytes` because its layout is not guaranteed. But perhaps you're just looking for `str: AsBytes`? That we have. If you have `s: String`, you can do `s.as_str().as_bytes()`.

**Comment by joshlf** [comment]
I'm gonna close this so it doesn't show up in our active issues, but feel free to continue the conversation.

**Comment by miaomiao1992** [comment]
how about convert String into usize + u8 arrays ?

**Comment by jswrenn** [comment]
Since `String` is a buffer of dynamic length, there's no general way to turn it into an array of static length. You can turn `String` into a slice of dynamic length with [`.as_bytes()`](https://doc.rust-lang.org/stable/std/string/struct.String.html#method.as_bytes).

**Comment by miaomiao1992** [comment]
> Since `String` is a buffer of dynamic length, there's no general way to turn it into an array of static length. You can turn `String` into a slice of dynamic length with [`.as_bytes()`](https://doc.rust-lang.org/stable/std/string/struct.String.html#method.as_bytes).

yes,you are right. i mean we can transfer String in to [u8,n1] prefix and [u8,n2]. [u8,n1] is serialized from usize and represents the length of aString，and [u8,n2] is deserialized from the content of this String.
