### ISSUE TITLE
Optimize caching in CI

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#85]
In CI, we use the [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) GitHub Action to cache certain build artifacts across runs. However, it seems from the README that we might be using it in a suboptimal way. A few observations:
- Zerocopy has only one dependency, and `rust-cache` only caches dependencies, not crate artifacts (note that zerocopy-derive has more dependencies - and dependencies that are expensive to compile - so presumably benefits much more than zerocopy)
- We generate a custom cache key which includes:
  - A hash of the Cargo features, but this presumably shouldn't have any effect on dependencies (at least in our case, since none of our Cargo features depend on dependencies' Cargo features)
  - A hash of `**/Cargo.lock`, but this is documented to be the default behavior anyway

We should:
- Figure out if there's a way to squeeze more benefit out for zerocopy (can we get `rust-cache` to cache any more artifacts?)
- Don't include Cargo features in the cache
- Don't include a hash of `**/Cargo.lock` in the cache
- Go back over our use of `rust-cache` and its README with a fine toothed comb and see what else we're doing suboptimally

cc @Swatinem in case there's anything obvious that jumps out at you!

**Comment by AntoniosBarotsis** [comment]
What do you mean by "crate artifacts"?

> Don't include a hash of `**/Cargo.lock` in the cache

I've seen this used everywhere, presumably as a means to invalidate the cache when the dependencies change so not sure why we would want to change this.

If you feel like you need more fine-grained control we could definitely checkout https://github.com/actions/cache which is what the rust-cache wraps around.

**Comment by Swatinem** [comment]
Your caching does not work, and won’t work with the upstream `actions/cache` either because you are not running CI on the master branch. There is no cache reuse across PRs, only from branch bases.

As for the cache config:
```
        key: "${{ matrix.toolchain }}-${{ matrix.target }}-${{ env.FEATURES_HASH }}-${{ hashFiles('**/Cargo.lock') }}"
```
The toolchain and lockfile hashes are part of the autogenerated, so you don’t need to list those manually.
I also doubt the extreme fanout to all target and feature permutations is really necessary. As only dependencies are cached, the feature flags do not really matter, and you might just as well test multiple permutations in a single run.

**Comment by glokta1** [comment]
> There is no cache reuse across PRs, only from branch bases.

What solution do you suggest? One workaround is to create a workflow that updates the cache on each commit to `main` as described [here](https://stackoverflow.com/questions/69365200/github-actions-how-to-cache-dependencies-between-workflow-runs-of-different-bra).

**Comment by Swatinem** [comment]
simply run workflow on the main branch as well

**Comment by glokta1** [comment]
Hey, would love your inputs on the above discussion @joshlf

**Comment by joshlf** [comment]
@AntoniosBarotsis 

> What do you mean by "crate artifacts"?
Anything that would speed up future compilation of the crate itself (such as the incremental compilation cache).

> > Don't include a hash of `**/Cargo.lock` in the cache
> 
> I've seen this used everywhere, presumably as a means to invalidate the cache when the dependencies change so not sure why we would want to change this.
`rust-cache` already does this by default, so having it explicitly is redundant.

@Swatinem 

> Your caching does not work, and won’t work with the upstream `actions/cache` either because you are not running CI on the master branch. There is no cache reuse across PRs, only from branch bases.
To clarify, if we enable the same workflow on the `main` branch, we will get caching benefits when the workflow is triggered by a PR?

> As for the cache config:
> 
> ```
>         key: "${{ matrix.toolchain }}-${{ matrix.target }}-${{ env.FEATURES_HASH }}-${{ hashFiles('**/Cargo.lock') }}"
> ```
> 
> The toolchain and lockfile hashes are part of the autogenerated, so you don’t need to list those manually. 
Yeah, definitely agreed that we should get rid of those.

> I also doubt the extreme fanout to all target and feature permutations is really necessary. As only dependencies are cached, the feature flags do not really matter, and you might just as well test multiple permutations in a single run.

Removing the feature flags makes sense to me. As for the targets, it seems like building with a different `--target` flag overwrites the build artifacts for other targets, so IIUC, it's still important to keep separate caches for different targets.

Specifically, I ran `cargo check --target <target-a> && cargo check --target <target-b> && cargo check --target <target-a>`, and the third invocation recompiled all of the dependency crates that had been compiled during the first invocation, leading me to believe that they were overwritten in the second invocation.

Thanks for your advice on this, btw! Good to know we've been doing all of this caching for absolutely no benefit whatsoever 😆

**Comment by glokta1** [comment]
Hey @joshlf can I get started on this issue then?

**Comment by joshlf** [comment]
Sure thing, @glokta1; thanks for volunteering!

Based on the preceding discussion, looks like the specific tasks are:
- From the `key`, remove the `matrix.toolchain`, `env.FEATURES_HASH`, and `hashFiles(...)` components
- Remove the job that generates the `FEATURES_HASH` environment variable
- Make the `ci.yml` workflow run on push to `main` as well as on PRs

**Comment by homersimpsons** [comment]
> What do you mean by "crate artifacts"?
> 
> > Don't include a hash of `**/Cargo.lock` in the cache
> 
> I've seen this used everywhere, presumably as a means to invalidate the cache when the dependencies change so not sure why we would want to change this.
> 
> If you feel like you need more fine-grained control we could definitely checkout https://github.com/actions/cache which is what the rust-cache wraps around.

Also there is an example configuration for Rust: https://github.com/actions/cache/blob/main/examples.md#rust---cargo

> ```
> - uses: actions/cache@v3
>   with:
>     path: |
>       ~/.cargo/bin/
>       ~/.cargo/registry/index/
>       ~/.cargo/registry/cache/
>       ~/.cargo/git/db/
>       target/
>     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
> ```
