### ISSUE TITLE
Leverage `core::marker::Freeze`

### ISSUE THREAD

**Issue by jswrenn** [google/zerocopy#941]
With https://github.com/rust-lang/rust/pull/121501, Rust may expose and subsequently stabilize the `Freeze` trait, which is automatically implemented for all types free of `UnsafeCell` (excluding by indirection such as `&UnsafeCell`). This is analogous to our `NoCell` trait, but our trait must be explicitly derived.

Once `Freeze` is stabilized, we should first emit a
```
where
     Self: Freeze
```
bound on the definition of `NoCell` when zerocopy is compiled with sufficiently-recent toolchains.

Then, we should consider whether to eliminate our `NoCell` trait altogether in favor of re-exporting `Freeze as NoCell`.

**Comment by joshlf** [comment]
We've decided that our `Immutable` will need to have slightly different semantics than stdlib `Freeze` - namely, it bans interior mutability *recursively* (ie, even via reference/pointer indirection), while `Freeze` does not. See #1155.
