### ISSUE TITLE
Stable and nightly toolchain roller failing

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#947]
https://github.com/google/zerocopy/actions/runs/8030574585

**Comment by jswrenn** [comment]
This is occurring because the Rust replacement to `./cargo.sh` is not setting its exit code appropriately depending on the outcome of its inner invocation. Its exit code is always `0`, and so Github Actions considers all of our CI steps to have unconditionally passed.

**Comment by joshlf** [comment]
Fixed in a bunch of PRs culminating in #948.
